Repository gazebosim/gz-msgs, pull requests merged in 2020-05, with the labels that each got.

#49 [ign-msgs4] Workflow updates
  .github/CODEOWNERS
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  codecov.yml
Labels: 📜 blueprint

#50 [ign-msgs5] Workflow updates
  .github/CODEOWNERS
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  codecov.yml
Labels: 🏰 citadel, 🔮 dome

#47 Add Cone Geometry Message
  proto/ignition/msgs/conegeom.proto
  proto/ignition/msgs/geometry.proto
Labels: enhancement, 🔮 dome

#53 Merge 4 -> 5
  Changelog.md
  proto/ignition/msgs/sdf_generator_config.proto
Labels: 🏰 citadel, 🔮 dome

#54 ⬆️ Bump to 5.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🔮 dome

#58 Multi enitty
  CMakeLists.txt
  Changelog.md
  proto/ignition/msgs/entity_factory_v.proto
Labels: 📜 blueprint

#59 4 to 5 may2020
  .gitignore
  CMakeLists.txt
  Changelog.md
  proto/ignition/msgs/entity_factory_v.proto
Labels: 🏰 citadel, 🔮 dome

#62 Feature/add visual arrow and axis
  proto/ignition/msgs/geometry.proto
  proto/ignition/msgs/marker.proto
Labels: enhancement
