Repository gazebosim/gz-msgs, pull requests merged in 2020-08, with the labels that each got.

#73 Add Focal CI
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
Labels: 📜 blueprint

#74 4 ➡️ 5
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
Labels: 🏰 citadel

#75 5 ➡️ 6
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
Labels: 🔮 dome

#76 Included autogenerated code to the ign_create_docs function
  CMakeLists.txt
Labels: boost the docs, documentation, 🔮 dome

#79 [backport Blueprint] Included autogenerated code to the ign_create_docs function (#76)
  CMakeLists.txt
Labels: documentation, 📜 blueprint

#78 [backport Citadel] Included autogenerated code to the ign_create_docs function (#76)
  CMakeLists.txt
Labels: documentation, 🏰 citadel
