Repository gazebosim/gz-msgs, pull requests merged in 2020-12, with the labels that each got.

#104 Prepare for 6.1.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#107 Make ignstrtok private to Utility.cc
  src/Utility.cc
Labels: 🏢 edifice, 🔮 dome

#106 Add JointTrajectory message
  proto/ignition/msgs/joint_trajectory.proto
  proto/ignition/msgs/joint_trajectory_point.proto
Labels: 🏢 edifice, 🔮 dome

#110 Added statistics message
  proto/ignition/msgs/statistic.proto
Labels: 🏰 citadel

#114 Prepare for 5.5.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#115 5 ➡️ 6
  Changelog.md
  proto/ignition/msgs/statistic.proto
Labels: 🏢 edifice, 🔮 dome

#117 [Backport] Add JointTrajectory message (#106)
  proto/ignition/msgs/joint_trajectory.proto
  proto/ignition/msgs/joint_trajectory_point.proto
Labels: 🏰 citadel

#116 ⬆️ 6.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice, 🔮 dome

#119 Add a is_periodic_change field to SerializedStateMap
  proto/ignition/msgs/serialized_map.proto
Labels: enhancement

#118 Added render order to material msgs
  proto/ignition/msgs/material.proto
Labels: 🏢 edifice, 🔮 dome

#120 Utility_TEST: adjust expectations for 32-bit arch
  src/Utility_TEST.cc
Labels: 🏢 edifice, 🔮 dome

#121 ⬆️ 5.6.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel
