Repository gazebosim/gz-msgs, pull requests merged in 2020-11, with the labels that each got.

#96 Resolve updated codecheck issues
  src/ign.cc
Labels: 📜 blueprint

#97 4 to 5
  src/ign.cc
Labels: 🏰 citadel

#98 5 to 6
  .github/workflows/ci.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
  src/Utility.cc
  src/ign.cc
Labels: 🔮 dome

#99 ⬆️ Bump to 5.4.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#102 Merge 5 to 6
  Changelog.md
Labels: 🏢 edifice, 🔮 dome
