Repository gazebosim/gz-msgs, pull requests merged in 2020-09, with the labels that each got.

#82 Use modern CMake targets when including ignition-math
  src/CMakeLists.txt
Labels: 🏰 citadel

#81 Added utility functions to convert between msg::time and std::chrono time_point
  CMakeLists.txt
  include/ignition/msgs/Utility.hh
  src/Utility.cc
  src/Utility_TEST.cc
Labels: beta, enhancement, 🔮 dome

#84 5 ➡️ 6
  src/CMakeLists.txt
Labels: beta, 🔮 dome

#85 Convert functions between duration and ignition::time
  include/ignition/msgs/Utility.hh
  src/Utility.cc
  src/Utility_TEST.cc
Labels: beta, 🔮 dome

#86 ⬆️ 6.0.0~pre2
  CMakeLists.txt
Labels: 🔮 dome

#87 Prepare for 6.0.0 release.
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#89 bump readme versions
  README.md
Labels: 🔮 dome

#88 bump versions in readme
  README.md
Labels: 🏰 citadel

#90 bump readme math version
  README.md
Labels: 📜 blueprint
