Repository gazebosim/gz-msgs, pull requests merged in 2021-08, with the labels that each got.

#172 Adds PerformanceSensorMetrics proto message.
  proto/ignition/msgs/performance_sensor_metrics.proto
Labels: 🏰 citadel

#174 5 ➡️ 6
  CMakeLists.txt
  proto/ignition/msgs/performance_sensor_metrics.proto
  tools/CMakeLists.txt
Labels: 🔮 dome

#173 🎈 5.8.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#165 Add BoundingBox Msg
  proto/ignition/msgs/annotated_axis_aligned_2d_box.proto
  proto/ignition/msgs/annotated_axis_aligned_2d_box_v.proto
  proto/ignition/msgs/annotated_oriented_3d_box.proto
  proto/ignition/msgs/annotated_oriented_3d_box_v.proto
  proto/ignition/msgs/axis_aligned_2d_box.proto
  proto/ignition/msgs/oriented_3d_box.proto
Labels: 🏯 fortress

#176 🎈 6.6.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome
