Repository gazebosim/gz-msgs, pull requests merged in 2021-05, with the labels that each got.

#161 fixed a comment in the Image.proto file
  proto/ignition/msgs/image.proto
Labels: 🏢 edifice

#162 Add particle scatter ratio field to particle emitter
  proto/ignition/msgs/particle_emitter.proto
Labels: 🏯 fortress

#163 7 ➡️ 8
  Changelog.md
  proto/ignition/msgs/actor.proto
  proto/ignition/msgs/image.proto
  proto/ignition/msgs/particle_emitter_v.proto
Labels: 🏯 fortress

#159 Port codecov to new configuration
  .github/workflows/ci.yml
Labels: 🏯 fortress

#164 Remove tools/code_check and update codecov
  .github/workflows/ci.yml
  CMakeLists.txt
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cpplint.py
Labels: 🏰 citadel
