Repository gazebosim/gz-msgs, pull requests merged in 2021-01, with the labels that each got.

#126 Add windows installation; move installation in README to tutorial
  README.md
  tutorials.md.in
  tutorials/install.md
Labels: 🏰 citadel

#128 Added capsule and ellipsoid geom msgs
  proto/ignition/msgs/capsulegeom.proto
  proto/ignition/msgs/ellipsoidgeom.proto
  proto/ignition/msgs/geometry.proto
  proto/ignition/msgs/marker.proto
  src/Utility.cc
  src/Utility_TEST.cc
Labels: 🏢 edifice

#129 Add std:: to strings in Generator.cc/hh
  src/Generator.cc
  src/Generator.hh
Labels: 🔮 dome

#127 Particle emitter message
  proto/ignition/msgs/particle_emitter.proto
Labels: 🔮 dome

#130 Add double sided field to material
  proto/ignition/msgs/material.proto
Labels: 🏢 edifice
