Repository gazebosim/gz-msgs, pull requests merged in 2021-09, with the labels that each got.

#180 6 ➡️ 7
  CMakeLists.txt
  Changelog.md
  proto/ignition/msgs/performance_sensor_metrics.proto
  tools/CMakeLists.txt
Labels: beta, 🏢 edifice

#181 🎈 7.2.0
  CMakeLists.txt
  Changelog.md
Labels: beta, 🏢 edifice

#177 🌐 Spherical coordinates conversion and commands
  include/ignition/msgs/Utility.hh
  proto/ignition/msgs/entity_factory.proto
  proto/ignition/msgs/spherical_coordinates.proto
  src/Utility.cc
  src/Utility_TEST.cc
Labels: beta, 🏯 fortress

#179 scene.proto: add shadow_caster_material_name
  proto/ignition/msgs/scene.proto
Labels: beta, 🏯 fortress

#183 🎈 8.0.0~pre1
  Changelog.md
Labels: beta, 🏯 fortress

#184 🥳 Update ign-tools issue on README
  README.md
Labels: documentation, 🏰 citadel, beta, Gazebo 1️1️

#185 Added macos install instructions
  tutorials/install.md
Labels: 🏯 fortress
