Repository gazebosim/gz-msgs, pull requests merged in 2021-04, with the labels that each got.

#149 Added `particle_emitter` vector message
  proto/ignition/msgs/particle_emitter_v.proto
Labels: 🔮 dome

#154 6 5 0 prep
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#155 Bumps in fortress : ign-msgs8
  README.md
Labels: documentation

#157 6 ➡️ 7
  CMakeLists.txt
  Changelog.md
  proto/ignition/msgs/actor.proto
  proto/ignition/msgs/particle_emitter_v.proto
Labels: 🏢 edifice

#158 🎈 7.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice
