Repository gazebosim/gz-msgs, pull requests merged in 2021-07, with the labels that each got.

#95 Bazel updates for msgs6
  BUILD.bazel
  ign_msg_gen.bzl
  protobuf.bzl
  test/BUILD.bazel
Labels: 🔮 dome

#169 5 ➡️ 6
  .github/workflows/ci.yml
  CMakeLists.txt
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cpplint.py
Labels: 🔮 dome

#170 6 ➡️ 7
  .github/workflows/ci.yml
  BUILD.bazel
  CMakeLists.txt
  ign_msg_gen.bzl
  protobuf.bzl
  test/BUILD.bazel
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cpplint.py
Labels: 🏢 edifice

#171 7 ➡️ 8
  BUILD.bazel
  CMakeLists.txt
  ign_msg_gen.bzl
  protobuf.bzl
  test/BUILD.bazel
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cpplint.py
Labels: 🏯 fortress
