Repository gazebosim/gz-msgs, pull requests merged in 2021-03, with the labels that each got.

#138 Add ignition version of nav_msgs/OccupancyGrid
  proto/ignition/msgs/occupancy_grid.proto
Labels: 🔮 dome

#139 Prepare for 6.4.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#140 6 ➡️ 7
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
  Changelog.md
  Migration.md
  proto/ignition/msgs/occupancy_grid.proto
  proto/ignition/msgs/particle_emitter.proto
Labels: 🏢 edifice

#141 Master branch updates
  .github/workflows/ci.yml
  README.md
Labels: 🏰 citadel

#142 5 ➡️ 6
  .github/workflows/ci.yml
  README.md
Labels: 🔮 dome

#143 Backport: Add ignition version of nav_msgs/OccupancyGrid (#138)
  proto/ignition/msgs/occupancy_grid.proto
Labels: 🏰 citadel

#144 Prepare for 5.7.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#145 5 to 6
  Changelog.md
Labels: 🔮 dome

#146 6 ➡️ 7
  .github/workflows/ci.yml
  Changelog.md
  README.md
Labels: beta, 🏢 edifice

#147 🎈 7.0.0~pre1
  Changelog.md
Labels: beta, 🏢 edifice

#148 Update README.md
  README.md
Labels: 🏢 edifice
