Repository gazebosim/gz-msgs, pull requests merged in 2022-09, with the labels that each got.

#303 Remove incorrect redirection header
  include/ignition/msgs/test_config.h
Labels: bug, 🌱 garden

#301 gz_TEST: one more ign -> gz
  tools/gz_TEST.cc
Labels: bug, 🌱 garden

#304 Move generated message to details folder
  CMakeLists.txt
  src/CMakeLists.txt
  src/Generator.cc
  tools/gz_msgs_generate.py
Labels: 🌱 garden

#305 Update Changelog for 9.0.0
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#308 Prepare for 8.7.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress
