Repository gazebosim/gz-msgs, pull requests merged in 2022-03, with the labels that each got.

#225 Add Ubuntu Jammy CI
  .github/workflows/ci.yml
Labels: 🏯 fortress

#205 Add wheel slip message definition
  proto/ignition/msgs/wheel_slip_parameters_cmd.proto
Labels: enhancement, 🏢 edifice

#228 change is_light_on to is_light_off
  proto/ignition/msgs/light.proto
Labels: 🌱 garden

#229 Remove Bionic from future releases (Garden+)
  .github/workflows/ci.yml
  README.md
  bitbucket-pipelines.yml
Labels: documentation, tests, 🌱 garden

#227 Add docs to wheel_slip_parameters_cmd.proto
  proto/ignition/msgs/wheel_slip_parameters_cmd.proto
Labels: enhancement, 🏢 edifice

#232 🎈 5.9.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, Gazebo 1️1️

#233 Merge 5 -> 7
  .github/workflows/ci.yml
  Changelog.md
  include/ignition/msgs/PointCloudPackedUtils.hh
  proto/ignition/msgs/navsat.proto
Labels: 🏢 edifice

#234 Prepare for 7.3.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#226 Merge 7 -> 8
  .github/workflows/ci.yml
  Changelog.md
  include/ignition/msgs/PointCloudPackedUtils.hh
  proto/ignition/msgs/wheel_slip_parameters_cmd.proto
Labels: 🏯 fortress

#237 Prepare for 8.3.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress
