Repository gazebosim/gz-msgs, pull requests merged in 2022-08, with the labels that each got.

#289 Merge ign-msgs8 ➡️ main
  src/Utility.cc
  src/Utility_TEST.cc
Labels: 🌱 garden

#290 🎈 8.6.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#291 ign -> gz Migrate config and log directories : gz-msgs
  README.md
Labels: 🌱 garden, ign to gz

#293 ign -> gz : Remove redundant namespace references
  src/PointCloudPackedUtils_TEST.cc
  src/Utility_TEST.cc
  src/ign.cc
Labels: 🏰 citadel, ign to gz

#241 Add message definitions for the parameter component
  proto/ignition/msgs/parameter.proto
  proto/ignition/msgs/parameter_declaration.proto
  proto/ignition/msgs/parameter_declarations.proto
  proto/ignition/msgs/parameter_error.proto
  proto/ignition/msgs/parameter_name.proto
  proto/ignition/msgs/parameter_value.proto
Labels: enhancement, 🏯 fortress

#295 Merge ign-msgs5 ➡️ ign-msgs8
  src/PointCloudPackedUtils_TEST.cc
  src/Utility_TEST.cc
  src/ign.cc
Labels: 🏯 fortress

#296 Prepare for 8.7.0 prerelease
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#298 ParemeterError: rename NO_ERROR to SUCCESS
  proto/ignition/msgs/parameter_error.proto
Labels: bug, 🏯 fortress

#299 Prepare for 8.7.0~pre2 prerelease
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress
