Repository gazebosim/gz-msgs, pull requests merged in 2022-04, with the labels that each got.

#238 Add Dataframe message
  proto/ignition/msgs/dataframe.proto
Labels: 🏯 fortress, mbzirc

#239 ⬆️ 8.4.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#242 Generator: Add missing std namespace to string arguments for Protobuf 3.20 compatibility
  src/Generator.cc
  src/Generator.hh
Labels: 🏰 citadel, Gazebo 1️1️

#243 Use SuppressWarning from ign-utils
  Migration.md
  include/ignition/msgs/Filesystem.hh
  include/ignition/msgs/SuppressWarning.hh
  include/ignition/msgs/detail/SuppressWarning.hh
Labels: 🌱 garden

#244 8 ➡️ 9 (main)
  Changelog.md
  proto/ignition/msgs/dataframe.proto
Labels: 🌱 garden

#245 Remove SuppressWarning from msgs.hh to fix warnings
  Migration.md
  include/ignition/msgs/CMakeLists.txt
Labels: 🌱 garden

#246 Bumps in garden : ign-msgs9
  .github/ci/packages.apt
  CMakeLists.txt
  appveyor.yml
Labels: 🌱 garden

#248 Added visualize_visual to light.proto
  proto/ignition/msgs/light.proto
Labels: 🌱 garden

#247 Fix typo REGRESION/REGRESSION
  test/regression/CMakeLists.txt
Labels: 🏰 citadel, Gazebo 1️1️
