Repository gazebosim/gz-msgs, pull requests merged in 2022-10, with the labels that each got.

#310 5-11-0-pre1
  CMakeLists.txt
Labels: 🏰 citadel

#312 5 to 8
  Changelog.md
Labels: 🏯 fortress

#313 Merge ign-msgs8 ➡️ gz-msgs9
  Changelog.md
  proto/gz/msgs/lens.proto
  proto/gz/msgs/parameter.proto
  proto/gz/msgs/parameter_declaration.proto
  proto/gz/msgs/parameter_declarations.proto
  proto/gz/msgs/parameter_error.proto
  proto/gz/msgs/parameter_name.proto
  proto/gz/msgs/parameter_value.proto
  src/PointCloudPackedUtils_TEST.cc
  src/Utility_TEST.cc
  src/gz.cc
Labels: 🌱 garden
