Repository gazebosim/gz-msgs, pull requests merged in 2022-06, with the labels that each got.

#258 Merge ign-msgs5 ➡️ ign-msgs8
  appveyor.yml
  bitbucket-pipelines.yml
Labels: 🏯 fortress

#259 ign -> gz Environment Variable Migration : gz-msgs
  Migration.md
  include/gz/msgs/Factory.hh
  src/Factory.cc
Labels: 🌱 garden, ign to gz

#254 Bash completion for flags
  CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/msgs.bash_completion.sh
  tools/CMakeLists.txt
  tools/ign_TEST.cc
Labels: 🏰 citadel, Gazebo 1️1️, OOBE 📦✨, needs upstream release

#263 [ign -> gz] CMake functions
  CMakeLists.txt
  conf/CMakeLists.txt
  conf/msgs.yaml.in
  include/gz/msgs/CMakeLists.txt
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
  tools/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#260 ign -> gz Upstream Macro Migration : gz-msgs
  include/gz/msgs/Factory.hh
  include/gz/msgs/Filesystem.hh
  include/gz/msgs/Utility.hh
  include/ignition/msgs/Factory.hh
  proto/gz/msgs/fuel_metadata.proto
  proto/gz/msgs/occupancy_grid.proto
  proto/gz/msgs/pointcloud_packed.proto
  src/Generator.cc
  src/Utility.cc
  src/Utility_TEST.cc
  src/cmd/cmdmsgs.rb.in
  src/ign.cc
  src/ign.hh
  tools/ign_TEST.cc
Labels: 🌱 garden, ign to gz, needs upstream release

#262 ign -> gz CLI Migration : gz-msgs
  BUILD.bazel
  CMakeLists.txt
  Changelog.md
  Migration.md
  README.md
  conf/CMakeLists.txt
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/cmdmsgs.rb.in
  src/gz.cc
  src/gz.hh
  tools/CMakeLists.txt
  tools/gz_TEST.cc
  tutorials/install.md
Labels: 🌱 garden, ign to gz

#264 Merge ign-msgs5 ➡️ ign-msgs8
  CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/msgs.bash_completion.sh
  tools/CMakeLists.txt
  tools/ign_TEST.cc
Labels: 🏯 fortress

#265 🎈 8.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#250 Rename CMake project to gz
  BUILD.bazel
  CMakeLists.txt
  src/CMakeLists.txt
  test/BUILD.bazel
Labels: 🌱 garden, ign to gz

#266 Migrate IGNITION- CMake variables
  CMakeLists.txt
  tutorials/cppgetstarted.md
Labels: 🌱 garden

#267 ign -> gz Partial Docs Migration and Project Name Followups : gz-msgs
  Changelog.md
  Migration.md
  README.md
  api.md.in
  appveyor.yml
  conf/msgs.yaml.in
  src/MessageTypes.hh.in
  tutorials.md.in
  tutorials/cppgetstarted.md
  tutorials/install.md
Labels: 🌱 garden
