Repository gazebosim/gz-msgs, pull requests merged in 2022-07, with the labels that each got.

#272 ign -> gz Provisional Finale: Source Migration : gz-msgs
  Changelog.md
  include/gz/msgs/Utility.hh
Labels: 🌱 garden, ign to gz

#275 Add ACTOR and WORLD types to entity
  proto/ignition/msgs/entity.proto
Labels: 🏰 citadel, Gazebo 1️1️, MBARI buoy

#273 Ignition -> Gazebo
  README.md
Labels: 🏰 citadel, tests, Gazebo 1️1️, QA

#277 🎈 5.10.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, Gazebo 1️1️

#278 Merge ign-msgs5 ➡️ ign-msgs8
  Changelog.md
  README.md
  proto/ignition/msgs/entity.proto
  proto/ignition/msgs/entity_wrench.proto
Labels: 🏯 fortress, MBARI buoy

#279 Allow moon and custom surfaces in spherical coords msg
  proto/gz/msgs/spherical_coordinates.proto
  src/Utility.cc
  src/Utility_TEST.cc
Labels: 🌱 garden

#282 Change IGN_DESIGNATION to GZ_DESIGNATION
  CMakeLists.txt
  api.md.in
  conf/CMakeLists.txt
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  tutorials.md.in
Labels: ign to gz

#283 Increase Utility coverage
  src/Utility.cc
  src/Utility_TEST.cc
Labels: 🏰 citadel, tests, Gazebo 1️1️, QA

#199 Added stepping bool to world statistics
  proto/gz/msgs/world_stats.proto
Labels: enhancement, 🌱 garden, Breaking change

#285 Safer move/rename for Windows
  tools/gz_msgs_generate.py
Labels: bug, Windows, 🌱 garden

#287 Merge ign-msgs4 ➡️ ign-msgs5
  CMakeLists.txt
  api.md.in
  conf/CMakeLists.txt
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  tutorials.md.in
Labels: 🏰 citadel, Gazebo 1️1️

#288 Merge ign-msgs5 ➡️ ign-msgs8
  CMakeLists.txt
  api.md.in
  conf/CMakeLists.txt
  src/CMakeLists.txt
  src/Utility.cc
  src/Utility_TEST.cc
  src/cmd/CMakeLists.txt
  tutorials.md.in
Labels: 🏯 fortress

#271 Add fluid added mass to inertial
  proto/gz/msgs/entity_wrench.proto
  proto/gz/msgs/inertial.proto
  src/Utility.cc
  src/Utility_TEST.cc
Labels: enhancement, 🌱 garden, MBARI buoy, Breaking change

#201 Adding additional fields to the camera sensor message
  Migration.md
  proto/gz/msgs/camerasensor.proto
  proto/gz/msgs/lens.proto
Labels: enhancement, 🌱 garden, Breaking change
