Repository gazebosim/gz-msgs, pull requests merged in 2023-08, with the labels that each got.

#369 Fix Github project automation for new project board
  .github/workflows/triage.yml
Labels: 🌱 garden

#333 add covariance fields to imu message
  proto/gz/msgs/imu.proto
Labels: beta, 🌱 garden

#370 Use `pull_request_target` for triage workflow
  .github/workflows/triage.yml
Labels: 🌱 garden

#320 Adds a message that allows loading environments via a topic
  include/gz/msgs/Utility.hh
  proto/gz/msgs/data_load_options.proto
  proto/gz/msgs/spherical_coordinates.proto
  src/Utility.cc
  src/Utility_TEST.cc
Labels: beta, 🌱 garden

#367 Remove ignition
  NEWS
  include/gz/msgs/Factory.hh
  src/CMakeLists.txt
  src/Factory.cc
  src/Generator.cc
Labels: 🎵 harmonic

#372 Merge gz-msgs9 ➡️ main
  .github/workflows/triage.yml
  include/gz/msgs/Utility.hh
  proto/gz/msgs/data_load_options.proto
  proto/gz/msgs/spherical_coordinates.proto
  src/Utility.cc
  src/Utility_TEST.cc
  tools/gz_msgs_generate.bzl
Labels: 🎵 harmonic

#373 Prepare for 9.5.0 Release
  CMakeLists.txt
  Changelog.md
Labels: beta, 🌱 garden

#374 Fix generator expression
  CMakeLists.txt
  core/src/DynamicFactory.cc
  core/src/MessageFactory.cc
  gz-msgs-extras.cmake.in
  test/integration/Factory_TEST.cc
Labels: beta, 🎵 harmonic

#375 Prepare for 10.0.0~pre1 Release
  Changelog.md
Labels: 🎵 harmonic

#376 Add pre1 suffix
  CMakeLists.txt
Labels: 🎵 harmonic

#377 Default to identity quaternion when not set
  core/include/gz/msgs/convert/Pose.hh
  test/integration/Utility_TEST.cc
Labels: 🎵 harmonic

#378 Prepare for 10.0.0~pre2 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#379 Support setting (or unsetting) dllexport macros
  cmake/gz_msgs_generate.cmake
  cmake/gz_msgs_protoc.cmake
  core/CMakeLists.txt
  tools/gz_msgs_generate.py
Labels: 🎵 harmonic

#380 Prepare for 10.0.0~pre3 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic
