Repository gazebosim/gz-msgs, pull requests merged in 2023-03, with the labels that each got.

#325 Support for bazel in garden
  BUILD.bazel
  src/CMakeLists.txt
  src/Factory_TEST.cc
  test/BUILD.bazel
  tools/BUILD.bazel
  tools/gz_msgs_generate.bzl
  tools/gz_msgs_generate.py
Labels: 🌱 garden

#329 Prepare for 9.4.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#330 Rename COPYING to LICENSE
  COPYING
  LICENSE
Labels: 🏰 citadel

#331 CI workflow: use checkout v3
  .github/workflows/ci.yml
Labels: 🏰 citadel

#332 Merge ign-msgs5 ➡️ ign-msgs8
  .github/workflows/ci.yml
  COPYING
  Changelog.md
  LICENSE
Labels: 🏯 fortress
