Repository gazebosim/gz-msgs, pull requests merged in 2023-06, with the labels that each got.

#348 Cherry-pick #346 to garden: GzProtobuf: Do not require version 3
  CMakeLists.txt
Labels: 🌱 garden

#349 Merge gz-msgs9 ➡️ main
  proto/gz/msgs/entity.proto
  proto/gz/msgs/fuel_metadata.proto
  proto/gz/msgs/marker.proto
  proto/gz/msgs/rest_response.proto
  src/Factory.cc
  src/Filesystem.cc
  src/Generator.cc
  src/Generator.hh
  src/Utility.cc
  src/gz.cc
  tools/gz_msgs_generate.bzl
Labels: 🎵 harmonic

#350 Merge ign-msgs5 ➡️ ign-msgs8
  CMakeLists.txt
Labels: 🏯 fortress

#347 Remove deprecated flag output_to_genfiles
  tools/gz_msgs_generate.bzl
Labels: 🌱 garden

#351 Merge gz-msgs9 ➡️ main
  CMakeLists.txt
  src/Generator.cc
Labels: 🎵 harmonic

#356 Unconditionally find the python interpreter
  CMakeLists.txt
Labels: 🎵 harmonic
